version: '3.1'
services:
  climax-database:
    image: 'postgres:12'
    container_name: climax_postgres
    ports:
      - '9099:5432'
    environment:
      POSTGRES_DB: climax_db
      POSTGRES_USER: climax_user
      POSTGRES_PASSWORD: climax

    networks:
      - climax-network


  climax-back:
    container_name: climax-back
    build: ./
    ports:
      - '8081:8081'
    depends_on:
      - climax-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://climax_postgres:5432/climax_db
      - SPRING_DATASOURCE_USERNAME=climax_user
      - SPRING_DATASOURCE_PASSWORD=climax
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - climax-network

networks:
  climax-network:
    driver: bridge
