# ================================================================
# PROFILE ACTIVATION : prod for production and dev for development
# ================================================================
spring:
  profiles:
    active: dev
